// app-angular/src/app/shared/components/form/form.component.ts
import {
  ChangeDetectorRef,
  Component,
  forwardRef,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import {
  AbstractControl,
  ControlValueAccessor,
  FormBuilder,
  FormGroup,
  NG_VALUE_ACCESSOR,
} from '@angular/forms';
import {
  debounceTime,
  distinctUntilChanged,
  firstValueFrom,
  Observable,
  Subject,
  takeUntil,
} from 'rxjs';

import { BaseQuery } from '../../types/base';

import {
  CheckboxOption,
  FormAction,
  FormOption,
  FtFormControl,
  RadioOption,
  SelectOption,
} from './form.model';

@Component({
  selector: 'app-form',
  standalone: false,
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FormComponent),
      multi: true,
    },
  ],
})
export class FormComponent<T = Record<string, unknown>>
  implements OnInit, OnDestroy, OnChanges, ControlValueAccessor
{
  @Input() option!: FormOption<T>;

  form!: FormGroup;
  isLoading = false;
  private destroy$ = new Subject<void>();
  private onChange = (value: Record<string, unknown>) => {};
  private onTouched = () => {};
  private controlOptionsCache = new Map<string, SelectOption[]>();

  constructor(
    private fb: FormBuilder,
    private cdr: ChangeDetectorRef
  ) {}

  // MARK: - Lifecycle Hooks
  ngOnInit(): void {
    this.buildForm();
    this.setupFormValueChanges();
    this.loadDynamicOptions();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['option'] && !changes['option'].firstChange) {
      this.buildForm();
      this.setupFormValueChanges();
      this.loadDynamicOptions();
    }
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  // MARK: - ControlValueAccessor Implementation
  writeValue(value: Record<string, unknown>): void {
    if (value && this.form) {
      this.form.patchValue(value, { emitEvent: false });
    }
  }

  registerOnChange(fn: (value: Record<string, unknown>) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.form) {
      if (isDisabled) {
        this.form.disable();
      } else {
        this.form.enable();
      }
    }
  }

  // MARK: - Form Building and Setup
  private buildForm(): void {
    const formControls: { [key: string]: unknown[] } = {};

    this.option.controls.forEach(control => {
      const validators = control.validators || [];
      const asyncValidators = control.asyncValidators || [];

      let defaultValue = control.defaultValue;
      if (
        this.option.initialData &&
        (this.option.initialData as Record<string, unknown>)[control.name] !== undefined
      ) {
        defaultValue = (this.option.initialData as Record<string, unknown>)[control.name];
      }

      formControls[control.name] = [
        {
          value: defaultValue || control.value || '',
          disabled: control.disabled || this.option.disabled || false,
        },
        validators,
        asyncValidators,
      ];
    });

    this.form = this.fb.group(formControls);

    // Apply initial data if provided
    if (this.option.initialData) {
      this.form.patchValue(this.option.initialData, { emitEvent: false });
    }
  }

  private setupFormValueChanges(): void {
    this.form.valueChanges
      .pipe(debounceTime(300), distinctUntilChanged(), takeUntil(this.destroy$))
      .subscribe(value => {
        this.onChange(value);
        this.handleConditionalLogic();
      });

    // Handle individual control changes
    this.option.controls.forEach(control => {
      if (control.onChange) {
        const formControl = this.form.get(control.name);
        if (formControl) {
          formControl.valueChanges.pipe(takeUntil(this.destroy$)).subscribe(value => {
            if (control.onChange) {
              control.onChange(value, this.form.value);
            }
          });
        }
      }
    });
  }

  // MARK: - Conditional Logic
  private handleConditionalLogic(): void {
    const formValue = this.form.value;

    this.option.controls.forEach(control => {
      const formControl = this.form.get(control.name);
      if (!formControl) return;

      // Handle showWhen condition
      if (control.showWhen) {
        const shouldShow = control.showWhen(formValue);
        // You can implement show/hide logic here if needed
      }

      // Handle enableWhen condition
      if (control.enableWhen) {
        const shouldEnable = control.enableWhen(formValue);
        if (shouldEnable && formControl.disabled) {
          formControl.enable({ emitEvent: false });
        } else if (!shouldEnable && formControl.enabled) {
          formControl.disable({ emitEvent: false });
        }
      }
    });
  }

  // MARK: - Action Handlers
  async onAction(action: FormAction): Promise<void> {
    if (action.disabled || action.loading) {
      return;
    }

    switch (action.type) {
      case 'submit':
        await this.handleSubmit(action);
        break;
      case 'reset':
        this.handleReset();
        break;
      case 'cancel':
        this.handleCancel();
        break;
      case 'custom':
        if (action.handler) {
          await this.executeHandler(action.handler);
        }
        break;
    }
  }

  private async handleSubmit(action: FormAction): Promise<void> {
    if (this.form.invalid) {
      this.markFormGroupTouched(this.form);
      return;
    }

    if (action.handler) {
      await this.executeHandler(action.handler);
    } else if (this.option.onSubmit) {
      await this.executeHandler(this.option.onSubmit);
    }
  }

  private handleReset(): void {
    this.form.reset();
    if (this.option.onReset) {
      this.option.onReset();
    }
  }

  private handleCancel(): void {
    if (this.option.onCancel) {
      this.option.onCancel();
    }
  }

  private async executeHandler(handler: Function): Promise<void> {
    try {
      this.isLoading = true;
      const result = handler(this.form.value);

      if (result instanceof Promise) {
        await result;
      } else if (result instanceof Observable) {
        await firstValueFrom(result);
      }
    } finally {
      this.isLoading = false;
      this.cdr.detectChanges();
    }
  }

  // MARK: - Form Utilities
  private markFormGroupTouched(formGroup: FormGroup): void {
    Object.keys(formGroup.controls).forEach(key => {
      const control = formGroup.get(key);
      if (control) {
        control.markAsTouched();
        if (control instanceof FormGroup) {
          this.markFormGroupTouched(control);
        }
      }
    });
  }

  getControl(name: string): AbstractControl | null {
    return this.form.get(name);
  }

  getErrorMessage(control: FtFormControl): string {
    const formControl = this.getControl(control.name);
    if (!formControl?.errors || !formControl.touched) {
      return '';
    }

    const errors = formControl.errors;
    const errorMessages = control.errorMessages || {};

    // Check for custom error messages first
    for (const errorKey in errors) {
      if (errorMessages[errorKey]) {
        return errorMessages[errorKey];
      }
    }

    // Default error messages
    const defaultMessages: { [key: string]: string } = {
      required: `${control.label} is required`,
      email: `${control.label} must be a valid email`,
      minlength: `${control.label} must be at least ${errors['minlength']?.requiredLength} characters`,
      maxlength: `${control.label} cannot exceed ${errors['maxlength']?.requiredLength} characters`,
      min: `${control.label} must be at least ${errors['min']?.min}`,
      max: `${control.label} cannot exceed ${errors['max']?.max}`,
      pattern: `${control.label} format is invalid`,
    };

    for (const errorKey in errors) {
      if (defaultMessages[errorKey]) {
        return defaultMessages[errorKey];
      }
    }

    return `${control.label} is invalid`;
  }

  isControlVisible(control: FtFormControl): boolean {
    if (control.hidden) {
      return false;
    }

    if (control.showWhen) {
      return control.showWhen(this.form.value);
    }

    return true;
  }

  // MARK: - Dynamic Options Loading
  private async loadDynamicOptions(): Promise<void> {
    const promises: Promise<void>[] = [];

    for (const control of this.option.controls) {
      if (control.options && typeof control.options === 'function') {
        const promise = this.loadOptionsForControl(control);
        promises.push(promise);
      }
    }

    await Promise.all(promises);
    this.cdr.detectChanges();
  }

  private async loadOptionsForControl(control: FtFormControl): Promise<void> {
    if (!control.options || typeof control.options !== 'function') {
      return;
    }

    try {
      // Set empty options initially to prevent errors
      this.controlOptionsCache.set(control.name, []);

      const optionsFunction = control.options as (
        input?: BaseQuery
      ) => Observable<SelectOption[]> | Promise<SelectOption[]> | SelectOption[];
      const result = optionsFunction();

      if (result instanceof Promise) {
        const options = await result;
        this.controlOptionsCache.set(control.name, options);
      } else if (result instanceof Observable) {
        result.pipe(takeUntil(this.destroy$)).subscribe(options => {
          this.controlOptionsCache.set(control.name, options);
          this.cdr.detectChanges();
        });
      } else if (Array.isArray(result)) {
        this.controlOptionsCache.set(control.name, result);
      }
    } catch (error) {
      // Log error for debugging but don't throw to prevent form from breaking
      this.controlOptionsCache.set(control.name, []);
    }
  }

  // MARK: - Options Getters
  getSelectOptions(control: FtFormControl): SelectOption[] {
    // Return cached options if available
    if (this.controlOptionsCache.has(control.name)) {
      return this.controlOptionsCache.get(control.name) || [];
    }

    if (!control.options) {
      return [];
    }

    if (Array.isArray(control.options)) {
      return control.options as SelectOption[];
    }

    // Handle Observable options
    if (control.options instanceof Observable) {
      control.options.pipe(takeUntil(this.destroy$)).subscribe(options => {
        this.controlOptionsCache.set(control.name, options);
        this.cdr.detectChanges();
      });
      return [];
    }

    // For function-based options, they should be loaded by loadDynamicOptions
    return [];
  }

  getRadioOptions(control: FtFormControl): RadioOption[] {
    if (!control.options || !Array.isArray(control.options)) {
      return [];
    }
    return control.options as RadioOption[];
  }

  getCheckboxOptions(control: FtFormControl): CheckboxOption[] {
    if (!control.options || !Array.isArray(control.options)) {
      return [];
    }
    return control.options as CheckboxOption[];
  }

  getColSpan(control: FtFormControl): number {
    return control.span || 24;
  }

  getColOffset(control: FtFormControl): number {
    return control.offset || 0;
  }

  // MARK: - Default Actions
  get hasDefaultActions(): boolean {
    return this.option.showDefaultActions !== false;
  }

  get defaultActions(): FormAction[] {
    if (!this.hasDefaultActions) {
      return [];
    }

    return [
      {
        type: 'submit',
        label: 'Submit',
        color: 'primary',
        icon: 'check',
        handler: (formValue: Record<string, unknown>) => {
          if (this.option.onSubmit) {
            this.option.onSubmit(formValue as T);
          }
        },
      },
      {
        type: 'cancel',
        label: 'Cancel',
        color: 'default',
        icon: 'close',
        handler: () => {
          if (this.option.onCancel) {
            this.option.onCancel();
          }
        },
      },
    ];
  }

  get allActions(): FormAction[] {
    const customActions = this.option.actions || [];
    const defaultActions = this.hasDefaultActions ? this.defaultActions : [];
    return [...customActions, ...defaultActions];
  }

  // MARK: - Public Methods
  getFormValue(): Record<string, unknown> {
    return this.form.value;
  }

  isFormValid(): boolean {
    return this.form.valid;
  }

  validateForm(): boolean {
    if (this.form.invalid) {
      this.markFormGroupTouched(this.form);
      return false;
    }
    return true;
  }

  submitForm(): void {
    if (this.validateForm()) {
      this.handleSubmit({
        type: 'submit',
        label: 'Submit',
        handler: this.option.onSubmit,
      } as FormAction);
    }
  }

  // Method to refresh options for a specific control
  async refreshControlOptions(controlName: string): Promise<void> {
    const control = this.option.controls.find(c => c.name === controlName);
    if (control) {
      await this.loadOptionsForControl(control);
      this.cdr.detectChanges();
    }
  }

  // Method to get current options for a control
  getCurrentOptions(controlName: string): SelectOption[] {
    return this.controlOptionsCache.get(controlName) || [];
  }

  // MARK: - TrackBy Functions
  trackByControlName(index: number, control: FtFormControl): string {
    return control.name;
  }

  trackByOptionValue(index: number, option: SelectOption | RadioOption | CheckboxOption): unknown {
    return option.value;
  }

  trackByActionType(index: number, action: FormAction): string {
    return `${action.type}-${action.label}`;
  }
}

<div class="kt-card w-full px-5 py-10">
  <form nz-form [formGroup]="form" [nzLayout]="option.layout || 'vertical'" class="dynamic-form">
    <div nz-row [nzGutter]="option.gutter || 16">
      <!-- Form Controls -->
      @for (control of option.controls; track trackByControlName($index, control)) {
        @if (isControlVisible(control)) {
          <div nz-col [nzSpan]="getColSpan(control)" [nzOffset]="getColOffset(control)" class="mb-4">
            <nz-form-item>
              <!-- Label -->
              @if (control.label && control.type !== 'hidden') {
                <nz-form-label [nzRequired]="control.required" [nzFor]="control.name">
                  {{ control.label }}
                </nz-form-label>
              }

              <!-- Control Wrapper -->
              <nz-form-control [nzErrorTip]="getErrorMessage(control)">
                <!-- Text Input -->
                @if (control.type === 'text' || control.type === 'email' || control.type === 'password') {
                  <nz-input-group [nzSize]="option.size || 'default'">
                    <input
                      nz-input
                      [type]="control.type"
                      [formControlName]="control.name"
                      [placeholder]="control.placeholder || ''"
                      [readonly]="control.readonly"
                      [maxlength]="control.maxLength || null"
                      [minlength]="control.minLength || null"
                    />
                  </nz-input-group>
                }

                <!-- Number Input -->
                @if (control.type === 'number') {
                  <nz-input-number
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || ''"
                    [nzMin]="control.min"
                    [nzMax]="control.max"
                    [nzStep]="control.step || 1"
                    [nzPrecision]="control.precision || null"
                    [nzSize]="option.size || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                  ></nz-input-number>
                }

                <!-- Textarea -->
                @if (control.type === 'textarea') {
                  <textarea
                    nz-input
                    [formControlName]="control.name"
                    [placeholder]="control.placeholder || ''"
                    [readonly]="control.readonly"
                    [rows]="control.rows || 4"
                    [nzAutosize]="control.autoSize || false"
                    [maxlength]="control.maxLength || null"
                  ></textarea>
                }

                <!-- Select -->
                @if (control.type === 'select') {
                  <nz-select
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || 'Please select'"
                    [nzAllowClear]="control.allowClear"
                    [nzShowSearch]="control.showSearch || control.searchable || isPaginatedControl(control.name)"
                    [nzServerSearch]="isPaginatedControl(control.name)"
                    [nzLoading]="isPaginatedLoading(control.name)"
                    [nzMode]="control.multiple ? 'multiple' : control.mode || 'default'"
                    [nzSize]="option.size || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                    (nzOnSearch)="isPaginatedControl(control.name) ? onSelectSearch(control.name, $event) : null"
                    (nzScrollToBottom)="isPaginatedControl(control.name) ? onSelectScrollToBottom(control.name) : null"
                  >
                    @for (opt of getSelectOptions(control); track trackByOptionValue($index, opt)) {
                      <nz-option [nzValue]="opt.value" [nzLabel]="opt.label" [nzDisabled]="opt.disabled"></nz-option>
                    }
                    <!-- Loading more indicator for paginated selects -->
                    @if (isPaginatedControl(control.name) && isPaginatedLoading(control.name)) {
                      <nz-option nzDisabled nzCustomContent>
                        <div class="flex items-center justify-center py-2">
                          <nz-spin nzSimple [nzSize]="'small'"></nz-spin>
                          <span class="ml-2 text-gray-500">Loading more...</span>
                        </div>
                      </nz-option>
                    }
                  </nz-select>
                }

                <!-- Radio Group -->
                @if (control.type === 'radio') {
                  <nz-radio-group
                    [formControlName]="control.name"
                    [nzSize]="option.size || 'default'"
                    [nzDisabled]="control.disabled"
                  >
                    @for (opt of getRadioOptions(control); track trackByOptionValue($index, opt)) {
                      <label nz-radio [nzValue]="opt.value" [nzDisabled]="opt.disabled">
                        {{ opt.label }}
                      </label>
                    }
                  </nz-radio-group>
                }

                <!-- Single Checkbox -->
                @if (control.type === 'checkbox') {
                  <label nz-checkbox [formControlName]="control.name" [nzDisabled]="control.disabled">
                    {{ control.placeholder || control.label }}
                  </label>
                }

                <!-- Multiple Choice (Checkbox Group) -->
                @if (control.type === 'multipleChoice') {
                  <nz-checkbox-group [formControlName]="control.name" [nzDisabled]="control.disabled">
                    <div nz-row>
                      @for (opt of getCheckboxOptions(control); track trackByOptionValue($index, opt)) {
                        <div nz-col [nzSpan]="24" class="mb-2">
                          <label
                            nz-checkbox
                            [nzValue]="opt.value"
                            [nzDisabled]="opt.disabled"
                            [nzChecked]="opt.checked"
                          >
                            {{ opt.label }}
                          </label>
                        </div>
                      }
                    </div>
                  </nz-checkbox-group>
                }

                <!-- Switch -->
                @if (control.type === 'switch') {
                  <nz-switch
                    [formControlName]="control.name"
                    [nzSize]="'default'"
                    [nzDisabled]="control.disabled"
                  ></nz-switch>
                }

                <!-- Date Picker -->
                @if (control.type === 'date') {
                  <nz-date-picker
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || 'Select date'"
                    [nzFormat]="control.format || 'yyyy-MM-dd'"
                    [nzShowTime]="control.showTime"
                    [nzDisabledDate]="control.disabledDate"
                    [nzSize]="(option.size === 'large' ? 'default' : option.size) || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                  ></nz-date-picker>
                }

                <!-- DateTime Picker -->
                @if (control.type === 'datetime') {
                  <nz-date-picker
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || 'Select date and time'"
                    [nzFormat]="control.format || 'yyyy-MM-dd HH:mm:ss'"
                    [nzShowTime]="true"
                    [nzDisabledDate]="control.disabledDate"
                    [nzSize]="(option.size === 'large' ? 'default' : option.size) || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                  ></nz-date-picker>
                }

                <!-- Time Picker -->
                @if (control.type === 'time') {
                  <nz-time-picker
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || 'Select time'"
                    [nzFormat]="control.format || 'HH:mm:ss'"
                    [nzSize]="(option.size === 'large' ? 'default' : option.size) || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                  ></nz-time-picker>
                }

                <!-- File Upload -->
                @if (control.type === 'file') {
                  <nz-upload [nzMultiple]="control.multiple" [nzShowUploadList]="true" [nzDisabled]="control.disabled">
                    <button nz-button [nzSize]="option.size || 'default'">
                      <i class="ki-outline ki-file-up"></i>

                      {{ control.placeholder }}
                    </button>
                  </nz-upload>
                }

                <!-- Rate -->
                @if (control.type === 'rate') {
                  <nz-rate
                    [formControlName]="control.name"
                    [nzDisabled]="control.disabled"
                    [nzAllowHalf]="true"
                  ></nz-rate>
                }

                <!-- Tag Input -->
                @if (control.type === 'tag') {
                  <nz-select
                    [formControlName]="control.name"
                    [nzPlaceHolder]="control.placeholder || 'Add tags'"
                    [nzMode]="'tags'"
                    [nzSize]="option.size || 'default'"
                    [nzDisabled]="control.disabled"
                    class="w-full"
                  >
                  </nz-select>
                }

                <!-- Range/Slider -->
                @if (control.type === 'range') {
                  <nz-slider
                    [formControlName]="control.name"
                    [nzMin]="control.min || 0"
                    [nzMax]="control.max || 100"
                    [nzStep]="control.step || 1"
                    [nzDisabled]="control.disabled"
                  ></nz-slider>
                }

                <!-- Color Picker -->
                @if (control.type === 'color') {
                  <nz-color-picker
                    [formControlName]="control.name"
                    [nzSize]="option.size || 'default'"
                    [nzDisabled]="control.disabled"
                  ></nz-color-picker>
                }

                <!-- Autocomplete -->
                @if (control.type === 'autocomplete') {
                  <nz-input-group [nzSize]="option.size || 'default'">
                    <input
                      nz-input
                      [formControlName]="control.name"
                      [placeholder]="control.placeholder || ''"
                      [readonly]="control.readonly"
                    />
                  </nz-input-group>
                }

                <!-- Hidden Input -->
                @if (control.type === 'hidden') {
                  <input type="hidden" [formControlName]="control.name" />
                }

                <!-- Rich Text Editor -->
                @if (control.type === 'richtext') {
                  <app-rich-text
                    [formControlName]="control.name"
                    [required]="control.required ?? false"
                  ></app-rich-text>
                }

                <!-- Custom Template -->
                @if (control.template) {
                  <ng-container
                    [ngTemplateOutlet]="control.template"
                    [ngTemplateOutletContext]="{
                      $implicit: getControl(control.name)?.value,
                      control: getControl(control.name),
                    }"
                  ></ng-container>
                }

                <!-- Description -->
                @if (control.description) {
                  <div class="ant-form-item-explain ant-form-item-explain-connected">
                    <div class="ant-form-item-explain-error">{{ control.description }}</div>
                  </div>
                }
              </nz-form-control>
            </nz-form-item>
          </div>
        }
      }
    </div>

    <!-- Form Actions -->
    @if (allActions.length > 0) {
      <div class="mt-5"></div>
      <nz-form-item>
        <nz-form-control>
          <nz-space>
            @for (action of allActions; track trackByActionType($index, action)) {
              <button
                nz-button
                [nzType]="action.color === 'primary' ? 'primary' : 'default'"
                [nzDanger]="action.color === 'danger'"
                [nzSize]="option.size || 'default'"
                [nzLoading]="action.loading || isLoading"
                [disabled]="action.disabled"
                (click)="onAction(action)"
                type="button"
              >
                @if (action.icon) {
                  <i [class]="action.icon + ' me-2'"></i>
                }
                {{ action.label }}
              </button>
            }
          </nz-space>
        </nz-form-control>
      </nz-form-item>
    }
  </form>
</div>

// app-react/src/components/partials/form/form.component.tsx
import { UploadOutlined } from '@ant-design/icons';
import {
  Button,
  Checkbox,
  Col,
  DatePicker,
  Form,
  FormInstance,
  Input,
  InputNumber,
  Radio,
  Row,
  Select,
  Switch,
  TimePicker,
  Upload,
} from 'antd';
import type { RcFile, UploadProps } from 'antd/es/upload';
import dayjs from 'dayjs';
import React, { forwardRef, useCallback, useEffect, useImperativeHandle, useState } from 'react';

import {
  BaseQuery,
  CheckboxOption,
  FormOption,
  FtFormControl,
  ListPaginate,
  PaginatedFormSelectOptions,
  RadioOption,
  SelectOption,
} from './models/form.model';

const { TextArea } = Input;
const { Option } = Select;

export interface FormComponentRef {
  validateForm: () => Promise<boolean>;
  getFormValue: () => Record<string, unknown>;
  setFormValue: (values: Record<string, unknown>) => void;
  resetForm: () => void;
  form: FormInstance;
}

export interface FormComponentProps<T = Record<string, unknown>> {
  formOptions: FormOption<T>;
  className?: string;
  style?: React.CSSProperties;
}

const FormComponent = forwardRef<FormComponentRef, FormComponentProps>(
  ({ formOptions, className, style }, ref) => {
    const [form] = Form.useForm();
    const [formValues, setFormValues] = useState<Record<string, unknown>>({});
    const [selectOptionsState, setSelectOptionsState] = useState<
      Record<string, PaginatedFormSelectOptions>
    >({});
    const [loading, setLoading] = useState(false);

    // Expose methods through ref
    useImperativeHandle(ref, () => ({
      validateForm: async () => {
        try {
          await form.validateFields();
          return true;
        } catch {
          return false;
        }
      },
      getFormValue: () => form.getFieldsValue(),
      setFormValue: (values: Record<string, unknown>) => {
        form.setFieldsValue(values);
        setFormValues(values);
      },
      resetForm: () => {
        form.resetFields();
        setFormValues({});
      },
      form,
    }));

    // Process initial data for special field types
    const processInitialData = useCallback(
      (data: Record<string, unknown>): Record<string, unknown> => {
        const processed = { ...data };

        formOptions.controls.forEach(control => {
          const value = processed[control.name];
          if (value !== undefined && value !== null) {
            switch (control.type) {
              case 'date':
              case 'datetime':
                if (typeof value === 'string' || typeof value === 'number') {
                  processed[control.name] = dayjs(value);
                }
                break;
              case 'time':
                if (typeof value === 'string') {
                  processed[control.name] = dayjs(value, control.format || 'HH:mm:ss');
                }
                break;
            }
          }
        });

        return processed;
      },
      [formOptions.controls]
    );

    // Initialize form data
    useEffect(() => {
      if (formOptions.initialData) {
        const processedData = processInitialData(formOptions.initialData);
        form.setFieldsValue(processedData);
        setFormValues(processedData);
      }
    }, [formOptions.initialData, form, processInitialData]);

    // Load select options
    const loadSelectOptions = async (control: FtFormControl, searchText = '', page = 1) => {
      if (!control.options) return;

      const key = control.name;
      setSelectOptionsState(prev => ({
        ...prev,
        [key]: { ...prev[key], loading: true },
      }));

      try {
        let options: SelectOption[] = [];
        let hasMore = false;
        let total = 0;

        if (Array.isArray(control.options)) {
          // Static options
          options = control.options as SelectOption[];
          total = options.length;
        } else if (typeof control.options === 'function') {
          if (control.usePagination) {
            // Paginated API
            const query: BaseQuery = {
              page,
              size: control.pageSize || 20,
              search: searchText,
            };
            const result = await (
              control.options as (input: BaseQuery) => Promise<ListPaginate<unknown>>
            )(query);
            options = result.data.map((item: unknown) => {
              const typedItem = item as Record<string, unknown>;
              return {
                label: (typedItem.name || typedItem.label || typedItem.title) as string,
                value: typedItem.id || typedItem.value,
              };
            });
            hasMore = result.hasMore;
            total = result.total;
          } else {
            // Non-paginated API
            const result = await (control.options as () => Promise<SelectOption[]>)();
            options = result;
            total = options.length;
          }
        }

        setSelectOptionsState(prev => ({
          ...prev,
          [key]: {
            options: page === 1 ? options : [...(prev[key]?.options || []), ...options],
            hasMore,
            currentPage: page,
            pageSize: control.pageSize || 20,
            total,
            loading: false,
            searchText,
          },
        }));
      } catch {
        setSelectOptionsState(prev => ({
          ...prev,
          [key]: { ...prev[key], loading: false },
        }));
      }
    };

    // Initialize select options
    useEffect(() => {
      formOptions.controls.forEach(control => {
        if (control.type === 'select' || control.type === 'autocomplete') {
          loadSelectOptions(control);
        }
      });
    }, [formOptions.controls]);

    // Handle form value changes
    const handleValuesChange = (
      changedValues: Record<string, unknown>,
      allValues: Record<string, unknown>
    ) => {
      setFormValues(allValues);

      // Handle control-specific onChange events
      Object.keys(changedValues).forEach(fieldName => {
        const control = formOptions.controls.find(c => c.name === fieldName);
        if (control?.onChange) {
          control.onChange(changedValues[fieldName], allValues);
        }
      });
    };

    // Handle form submission
    const handleSubmit = async (values: Record<string, unknown>) => {
      if (formOptions.onSubmit) {
        setLoading(true);
        try {
          await formOptions.onSubmit(values);
        } catch {
          // Handle error silently or through onSubmit callback
        } finally {
          setLoading(false);
        }
      }
    };

    // Render form control based on type
    const renderFormControl = (control: FtFormControl) => {
      // Check visibility conditions
      if (control.hidden) return null;
      if (control.showWhen && !control.showWhen(formValues)) return null;

      // Check enable conditions
      const isDisabled =
        control.disabled ||
        (control.enableWhen && !control.enableWhen(formValues)) ||
        formOptions.disabled;

      const commonProps = {
        placeholder: control.placeholder,
        disabled: isDisabled,
      };

      switch (control.type) {
        case 'text':
        case 'email':
        case 'password': {
          return (
            <Input
              {...commonProps}
              type={control.type}
              maxLength={control.maxLength}
              showCount={!!control.maxLength}
            />
          );
        }

        case 'number': {
          return (
            <InputNumber
              {...commonProps}
              min={control.min}
              max={control.max}
              step={control.step}
              precision={control.precision}
              style={{ width: '100%' }}
            />
          );
        }

        case 'textarea': {
          return (
            <TextArea
              {...commonProps}
              rows={control.rows || 4}
              autoSize={control.autoSize}
              maxLength={control.maxLength}
              showCount={!!control.maxLength}
            />
          );
        }

        case 'select':
        case 'autocomplete': {
          const selectState = selectOptionsState[control.name];
          const mode = control.mode === 'default' ? undefined : control.mode;

          return (
            <Select
              {...commonProps}
              mode={mode}
              allowClear={control.allowClear}
              showSearch={control.showSearch || control.searchable}
              loading={selectState?.loading}
              onSearch={control.searchable ? value => loadSelectOptions(control, value) : undefined}
            >
              {selectState?.options?.map(option => (
                <Option key={String(option.value)} value={option.value} disabled={option.disabled}>
                  {option.label}
                </Option>
              ))}
            </Select>
          );
        }

        case 'radio': {
          const radioOptions = control.options as RadioOption[];
          return (
            <Radio.Group {...commonProps}>
              {radioOptions?.map(option => (
                <Radio key={String(option.value)} value={option.value} disabled={option.disabled}>
                  {option.label}
                </Radio>
              ))}
            </Radio.Group>
          );
        }

        case 'checkbox': {
          const checkboxOptions = control.options as CheckboxOption[];
          return (
            <Checkbox.Group {...commonProps}>
              {checkboxOptions?.map(option => (
                <Checkbox
                  key={String(option.value)}
                  value={option.value}
                  disabled={option.disabled}
                >
                  {option.label}
                </Checkbox>
              ))}
            </Checkbox.Group>
          );
        }

        case 'switch': {
          return <Switch {...commonProps} />;
        }

        case 'date': {
          return (
            <DatePicker
              {...commonProps}
              format={control.format || 'YYYY-MM-DD'}
              style={{ width: '100%' }}
            />
          );
        }

        case 'datetime': {
          return (
            <DatePicker
              {...commonProps}
              showTime={control.showTime !== false}
              format={control.format || 'YYYY-MM-DD HH:mm:ss'}
              style={{ width: '100%' }}
            />
          );
        }

        case 'time': {
          return (
            <TimePicker
              {...commonProps}
              format={control.format || 'HH:mm:ss'}
              style={{ width: '100%' }}
            />
          );
        }

        case 'file': {
          const uploadProps: UploadProps = {
            beforeUpload: (_file: RcFile) => {
              // Handle file upload logic here
              return false; // Prevent auto upload
            },
          };

          return (
            <Upload {...uploadProps}>
              <Button icon={<UploadOutlined />}>Click to Upload</Button>
            </Upload>
          );
        }

        case 'richtext': {
          // This would typically use a rich text editor like React Quill
          return (
            <TextArea
              {...commonProps}
              rows={control.rows || 8}
              placeholder="Rich text editor would be implemented here"
            />
          );
        }

        case 'custom': {
          if (control.render) {
            return control.render(
              form.getFieldValue(control.name),
              value => form.setFieldValue(control.name, value),
              formValues
            );
          }
          return null;
        }

        case 'hidden': {
          return <Input type="hidden" />;
        }

        default: {
          return <Input {...commonProps} />;
        }
      }
    };

    // Render form actions
    const renderActions = () => {
      if (!formOptions.showDefaultActions && !formOptions.actions?.length) {
        return null;
      }

      const defaultActions = formOptions.showDefaultActions
        ? [
            {
              type: 'submit' as const,
              label: 'Submit',
              color: 'primary' as const,
              loading: loading,
              visible: true,
              disabled: false,
              icon: undefined,
            },
            {
              type: 'reset' as const,
              label: 'Reset',
              color: 'default' as const,
              loading: false,
              visible: true,
              disabled: false,
              icon: undefined,
              handler: () => {
                form.resetFields();
                setFormValues({});
                formOptions.onReset?.();
              },
            },
          ]
        : [];

      const allActions = [...defaultActions, ...(formOptions.actions || [])];

      return (
        <div className="flex gap-2 pt-4">
          {allActions.map((action, index) => {
            if (action.visible === false) return null;

            const handleClick = () => {
              if (action.type === 'submit') {
                form.submit();
              } else if (action.handler) {
                action.handler(form.getFieldsValue());
              }
            };

            return (
              <Button
                key={index}
                type={action.color === 'primary' ? 'primary' : 'default'}
                danger={action.color === 'danger'}
                loading={action.loading}
                disabled={action.disabled}
                onClick={handleClick}
                icon={action.icon}
              >
                {action.label}
              </Button>
            );
          })}
        </div>
      );
    };

    return (
      <div className={className} style={style}>
        <Form
          form={form}
          layout={formOptions.layout || 'vertical'}
          size={formOptions.size === 'default' ? 'middle' : formOptions.size}
          disabled={formOptions.disabled}
          labelCol={formOptions.labelCol}
          wrapperCol={formOptions.wrapperCol}
          onValuesChange={handleValuesChange}
          onFinish={handleSubmit}
          validateTrigger={formOptions.validateTrigger || 'onChange'}
        >
          <Row gutter={formOptions.gutter || 16}>
            {formOptions.controls.map(control => {
              if (control.hidden || (control.showWhen && !control.showWhen(formValues))) {
                return null;
              }

              return (
                <Col key={control.name} span={control.span || 24} offset={control.offset || 0}>
                  <Form.Item
                    name={control.name}
                    label={control.label}
                    rules={control.rules}
                    help={control.description}
                    labelCol={control.labelCol}
                    wrapperCol={control.wrapperCol}
                    required={control.required}
                    hidden={control.hidden}
                  >
                    {renderFormControl(control)}
                  </Form.Item>
                </Col>
              );
            })}
          </Row>

          {renderActions()}
        </Form>
      </div>
    );
  }
);

FormComponent.displayName = 'FormComponent';

export default FormComponent;
