// react-vip-pro/src/components/form/form-elements/FileInputExample.tsx
import ComponentCard from "../../common/card.component";
import FileInput from "../input/FileInput";
import Label from "../Label";

export default function FileInputExample() {
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      console.log("Selected file:", file.name);
    }
  };

  return (
    <ComponentCard title="File Input">
      <div>
        <Label>Upload file</Label>
        <FileInput onChange={handleFileChange} className="custom-class" />
      </div>
    </ComponentCard>
  );
}

// angular-vip-pro/src/app/shared/components/form/form-elements/file-input-example/file-input-example.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";

import { ComponentCardComponent } from "../../../common/component-card/component-card.component";
import { FileInputComponent } from "../../input/file-input.component";
import { LabelComponent } from "../../label/label.component";

@Component({
  selector: "app-file-input-example",
  imports: [
    CommonModule,
    ComponentCardComponent,
    LabelComponent,
    FileInputComponent,
  ],
  template: `
    <app-component-card title="File Input">
      <div>
        <app-label>Upload file</app-label>
        <app-file-input
          (change)="handleFileChange($event)"
          className="custom-class"
        ></app-file-input>
      </div>
    </app-component-card>
  `,
})
export class FileInputExampleComponent {
  handleFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      console.log("Selected file:", file.name);
    }
  }
}
