// react-vip-pro/src/components/form/form-elements/ToggleSwitch.tsx
import ComponentCard from "../../common/card.component";
import Switch from "../switch/Switch";

export default function ToggleSwitch() {
  const handleSwitchChange = (checked: boolean) => {
    console.log("Switch is now:", checked ? "ON" : "OFF");
  };
  return (
    <ComponentCard title="Toggle switch input">
      <div className="flex gap-4">
        <Switch
          label="Default"
          defaultChecked={true}
          onChange={handleSwitchChange}
        />
        <Switch
          label="Checked"
          defaultChecked={true}
          onChange={handleSwitchChange}
        />
        <Switch label="Disabled" disabled={true} />
      </div>{" "}
      <div className="flex gap-4">
        <Switch
          label="Default"
          defaultChecked={true}
          onChange={handleSwitchChange}
          color="gray"
        />
        <Switch
          label="Checked"
          defaultChecked={true}
          onChange={handleSwitchChange}
          color="gray"
        />
        <Switch label="Disabled" disabled={true} color="gray" />
      </div>
    </ComponentCard>
  );
}

// angular-vip-pro/src/app/shared/components/form/form-elements/toggle-switch/toggle-switch.component.ts
import { Component } from '@angular/core';

import { ComponentCardComponent } from '../../../common/component-card/component-card.component';
import { SwitchComponent } from '../../input/switch.component';

@Component({
  selector: 'app-toggle-switch',
  imports: [
    SwitchComponent,
    ComponentCardComponent,
  ],
  templateUrl: './toggle-switch.component.html',
  styles: ``
})
export class ToggleSwitchComponent {

  handleSwitchChange(checked: boolean) {
    console.log('Switch is now:', checked ? 'ON' : 'OFF');
  }
}
