// app-angular/src/app/modules/auth/components/auth-layout/auth-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-auth-layout',
  standalone: false,
  templateUrl: './auth-layout.component.html',
})
export class AuthLayoutComponent {
  constructor() {}
}

<div
  class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-4 sm:px-6 lg:px-8"
>
  <div class="max-w-md w-full space-y-8">
    <div class="text-center">
      <h1 class="text-3xl font-bold text-gray-900 mb-2">Welcome</h1>
      <p class="text-gray-600">Please sign in to your account</p>
    </div>

    <div class="bg-white rounded-lg shadow-xl p-8">
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// app-react/src/components/layouts/auth/auth.layout.tsx
import { Card, Layout } from 'antd';
import React from 'react';
import { Outlet } from 'react-router-dom';

const { Content } = Layout;

const AuthLayout: React.FC = () => {
  return (
    <Layout className="min-h-screen bg-gradient-to-br from-neutral-50 to-neutral-100">
      <Content className="flex items-center justify-center p-6">
        <div className="w-full max-w-md">
          <Card className="shadow-xl border-0 p-2">
            <div className="text-center mb-8">
              <h1 className="text-2xl font-bold text-gray-900 mb-2">Welcome Back</h1>
              <p className="text-gray-600">Sign in to your admin account</p>
            </div>
            <Outlet />
          </Card>
        </div>
      </Content>
    </Layout>
  );
};

export default AuthLayout;
